### ISSUE TITLE
Unable to run the app, kotlin is ok

### ISSUE THREAD

**Issue by ninepi09** [newlogic/smartscanner-cordova#23]
## Current Behaviour

Cannot cordova android run, although i already use android@9 to install androidx in dependency,
this [https://github.com/dcendents/android-maven-gradle-plugin](url) is not working because abandon ,
i already use [https://github.com/idpass/smartscanner-capacitor](capasitor) aar for smartscannerlib-debug.aar and the release one, and the error from build gradle is :

> * What went wrong:
> Execution failed for task ':CordovaLib:compileDebugJavaWithJavac'.
> > Failed to calculate the value of task ':CordovaLib:compileDebugJavaWithJavac'
> property 'options.generatedSourceOutputDirectory'.
>    > Querying the mapped value of map(java.io.File property(org.gradle.api.file.
> Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$F
> ixedDirectory, (drive)\CordovaLib\build\generated\ap_generated_sources\debug\out)) org.g
> radle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@64da764c) b
> efore task ':CordovaLib:compileDebugJavaWithJavac' has completed is not supported

## Expected Behaviour

Cannot cordova android run, although i already use android@9 to install androidx in dependency,
this [https://github.com/dcendents/android-maven-gradle-plugin](url) is not working because abandon ,
i already use [https://github.com/idpass/smartscanner-capacitor](capasitor) aar for smartscannerlib-debug.aar and the release one, and the error from build gradle is :

> * What went wrong:
> Execution failed for task ':CordovaLib:compileDebugJavaWithJavac'.
> > Failed to calculate the value of task ':CordovaLib:compileDebugJavaWithJavac'
> property 'options.generatedSourceOutputDirectory'.
>    > Querying the mapped value of map(java.io.File property(org.gradle.api.file.
> Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$F
> ixedDirectory, (drive)\CordovaLib\build\generated\ap_generated_sources\debug\out)) org.g
> radle.api.internal.file.DefaultFilePropertyFactory$ToFileTransformer@64da764c) b
> efore task ':CordovaLib:compileDebugJavaWithJavac' has completed is not supported

## Steps to Reproduce the Problem

1. cordova platform remove android
cordova platform add android@9.0.0
2. cordova run android
3. use gradle 7.2
4. add <preference name="AndroidXEnabled" value="true" />
 in cofig.xml

## Context

- Version: 1.0.0
- Platform: android
- Cordova version: 10.0.0
![Untitled](https://user-images.githubusercontent.com/58588836/133727005-bfc35b14-e77d-416c-81ec-7db952555aff.png)

**Comment by rjmangubat23** [comment]
@ninepi09 please try our latest npm release [v0.4.0](https://www.npmjs.com/package/@idpass/smartscanner-cordova) this might fix the issue you are encountering. Thanks!
